### ISSUE TITLE
Translate to German

### ISSUE THREAD

**Issue by jturnbull** [incuna/django-extensible-profiles#18]
@annikavoss Can you please complete this po file?

https://github.com/incuna/django-extensible-profiles/raw/master/profiles/locale/de_DE/LC_MESSAGES/django.po

Thanks

**Comment by mlen108** [comment]
@annikavoss could you update on it please?
this issue needs to be done if we want to do this one https://github.com/incuna/almirall-ibs-community/issues/363

**Comment by jturnbull** [comment]
@Gem456 ^^

**Comment by annikavoss** [comment]
@jturnbull How do I open that in Poedit please?

**Comment by jturnbull** [comment]
in Chrome, File> Save as… then File > Open in Poedit

**Comment by annikavoss** [comment]
@jturnbull Context please:
Number of codes to generate
Length of codes to generate
Is this for the site, for admin or for backend?

**Comment by annikavoss** [comment]
@jturnbull Context please for 'Documentation'

**Comment by jturnbull** [comment]
I believe both are for the admin (so not very important). They are registration codes (like might be required to sign up)

**Comment by jturnbull** [comment]
'Documentation' is here: https://raw.github.com/incuna/django-extensible-profiles/master/profiles/templates/registration/password_change_done.html

it's a link to the admin documentation that no one has ever used…

**Comment by annikavoss** [comment]
Thanks.

Done, where do you want the file?

**Comment by jturnbull** [comment]
Email is fine and I'll update the repo?

**Comment by jturnbull** [comment]
Done in 345de86b722dcc75d829283599c3c46fb6c62730
